import project01Big from "./../img/projects/01-big.jpg";

import project02Big from "./../img/projects/02-big.jpg";

import project03Big from "./../img/projects/03-big.jpg";

const previewBase = `${process.env.PUBLIC_URL || ''}/project-previews`;

const projects = [
	{
		title: 'Burgers restaurant site',
		title_en: 'Burgers restaurant site',
		title_ru: 'Сайт бургер-ресторана',
		description: 'Static restaurant landing page with a strong hero section, menu-focused layout, and responsive styling.',
		description_en: 'Static restaurant landing page with a strong hero section, menu-focused layout, and responsive styling.',
		description_ru: 'Статическая промо-страница бургер-ресторана с выразительным hero-блоком, меню и адаптивной версткой.',
		skills: 'Angular, HTML, CSS',
		topics: ['frontend', 'landing-page', 'responsive-design'],
		img: `${previewBase}/burgers-restaurant-site.svg`,
		imgBig: project01Big,
		problem_en: 'Create a visually clear landing page for a food business with structured sections and responsive layout.',
		solution_en: 'Implemented a frontend page with reusable visual blocks, strong typography, and adaptive CSS.',
		result_en: 'Got a production-like landing page that presents the menu and core restaurant message clearly.',
		problem_ru: 'Создать понятный лендинг для фуд-проекта с логичной структурой блоков и адаптивной версткой.',
		solution_ru: 'Реализована frontend-страница с переиспользуемыми визуальными блоками, выразительной типографикой и адаптивными стилями.',
		result_ru: 'Получился цельный лендинг, который понятно показывает меню и ключевое сообщение ресторана.',
		type: 'site',
	},
	{
		title: 'js-marvel',
		title_en: 'js-marvel',
		title_ru: 'js-marvel',
		description: 'Vanilla JavaScript app for Marvel character search, pagination, and API-driven UI.',
		description_en: 'Vanilla JavaScript app for Marvel character search, pagination, and API-driven UI.',
		description_ru: 'Веб-приложение на JavaScript для поиска персонажей Marvel, пагинации и работы с внешним API.',
		skills: 'JavaScript, API, Bootstrap',
		topics: ['javascript', 'api-integration', 'frontend'],
		img: `${previewBase}/js-marvel.svg`,
		gitHubLink: 'https://github.com/xelvhk/js-marvel',
		problem_en: 'Build a frontend app that loads Marvel characters from an external API and keeps navigation understandable.',
		solution_en: 'Implemented API requests, pagination, routing, and reusable UI blocks with vanilla JavaScript and Bootstrap.',
		result_en: 'Delivered a browsable character catalog with responsive layout and a clear data-loading flow.',
		problem_ru: 'Собрать frontend-приложение, которое загружает персонажей Marvel из внешнего API и остается понятным в навигации.',
		solution_ru: 'Реализованы API-запросы, пагинация, маршрутизация и переиспользуемые UI-блоки на JavaScript и Bootstrap.',
		result_ru: 'Получился каталог персонажей с адаптивной версткой и понятным сценарием загрузки данных.',
		type: 'site',
	},
	{
		title: 'Farmgame site',
		title_en: 'Farmgame site',
		title_ru: 'Farmgame',
		description: 'Static promo landing page with themed visual design and responsive CSS layout.',
		description_en: 'Static promo landing page with themed visual design and responsive CSS layout.',
		description_ru: 'Статическая промо-страница с тематическим визуальным стилем и адаптивной CSS-версткой.',
		img: `${previewBase}/farmgame.svg`,
		imgBig: project02Big,
		skills: 'HTML, CSS',
		topics: ['html', 'css', 'landing-page'],
		gitHubLink: 'https://github.com/xelvhk/farmgame',
		problem_en: 'Build a themed promo page with clean visual hierarchy and basic responsiveness.',
		solution_en: 'Assembled semantic HTML structure and responsive CSS layout with custom visual styling.',
		result_en: 'Delivered a stable static website with clear sections and improved readability on different screens.',
		problem_ru: 'Собрать тематическую промо-страницу с чистой визуальной иерархией и базовой адаптивностью.',
		solution_ru: 'Сверстана семантичная HTML-структура и адаптивный CSS-лейаут с кастомным визуальным стилем.',
		result_ru: 'Получился стабильный статический сайт с понятными секциями и хорошей читаемостью на разных экранах.',
		type: 'site',
	},
	{
		title: 'fashion_store_with_React',
		title_en: 'fashion_store_with_React',
		title_ru: 'Fashion store',
		description: 'React storefront UI practice with component-based layout and responsive styling.',
		description_en: 'React storefront UI practice with component-based layout and responsive styling.',
		description_ru: 'Frontend-проект витрины магазина на React с компонентной структурой и адаптивной стилизацией.',
		img: `${previewBase}/fashion_store_with_React.svg`,
		imgBig: project03Big,
		skills: 'React, HTML, CSS',
		topics: ['react', 'frontend', 'ecommerce'],
		gitHubLink: 'https://github.com/xelvhk/fashion_store_with_React',
		problem_en: 'Create a storefront UI that feels modern and supports component-driven development.',
		solution_en: 'Built the interface with React components, reusable layouts, and clean style composition.',
		result_en: 'Produced a maintainable frontend baseline for e-commerce scenarios with improved UX consistency.',
		problem_ru: 'Сделать UI витрины, который выглядит современно и поддерживает компонентный подход разработки.',
		solution_ru: 'Интерфейс реализован на React-компонентах с переиспользуемыми лейаутами и чистой структурой стилей.',
		result_ru: 'Сформирована поддерживаемая frontend-база для e-commerce сценариев с более цельным UX.',
		type: 'site',
	},

];

export { projects };
